$("#wowslider-container").wowSlider({
    effect: "rotate",
    prev: "",
    next: "",
    duration: 20 * 100,
    delay: 20 * 100,
    width: 533,
    height: 360,
    autoPlay: true,
    autoPlayVideo: false,
    playPause: true,
    stopOnHover: false,
    loop: true,
    bullets: 1,
    caption: true,
    captionEffect: "parallax",
    controls: true,
    controlsThumb: false,
    responsive: 1,
    fullScreen: false,
    gestures: 2,
    onBeforeStep: 0,
    images: 0
});